before_script:
  - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD

stages:
  - build
  - deploy

build_image:
  stage: build
  image: registry.uicgroup.tech/devops/docker:dind
  script:
    - |
      if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
        ENV_TAG=latest
        TAG=dev
        ENV=$KEYS
      elif [ "$CI_COMMIT_REF_NAME" == "dev" ]; then
        ENV=$KEYS_DEV
        TAG=latest
        ENV_TAG=dev
      fi
    - cat $ENV > .env
    - make build-image TAG=$TAG SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=$ENV_TAG
    - make push-image TAG=$TAG SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=$ENV_TAG
  only:
    - master
    - dev 

deploy_to_prod:
  stage: deploy
  script:
    - docker pull $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
    - docker stop marjon_frontend
    - docker rm -f marjon_frontend
    - docker run -d -p 3000:3000 --name marjon_frontend $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
  only:
    - master
  tags:
    - marjon-vm

deploy_to_dev:
  stage: deploy
  script:
    - docker pull $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:dev
    - docker stop marjon.uz
    - docker rm -f marjon.uz
    - docker run -d -p 3046:3000 --name marjon.uz $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:dev
  only:
    - dev
  tags:
    - marjon-front-dev

